export const products = [
  {
    id: 1,
    title: "Air Max Sneakers",
    price: 120,
    category: "Shoes",
    image: "/images/air-max-sneakers.jpeg",
  },
  {
    id: 2,
    title: "Running Sneakers",
    price: 95,
    category: "Shoes",
    image: "/images/running.jpeg",
  },
  {
    id: 3,
    title: "Oversized Hoodie",
    price: 80,
    category: "Clothing",
    image: "/images/oversized-hoodie.jpeg",
  },
  {
    id: 4,
    title: "Graphic T-Shirt",
    price: 35,
    category: "Clothing",
    image: "/images/plain-shirt.jpeg",
  },
  {
    id: 5,
    title: "Wireless Headphones",
    price: 150,
    category: "Electronics",
    image: "/images/wireless-headphones.jpeg",
  },
  {
    id: 6,
    title: "Bluetooth Speaker",
    price: 110,
    category: "Electronics",
    image: "/images/speaker.jpeg",
  },
  {
    id: 7,
    title: "Leather Backpack",
    price: 90,
    category: "Bags",
    image: "/images/backpack.jpeg",
  },
  {
    id: 8,
    title: "Crossbody Bag",
    price: 65,
    category: "Bags",
    image: "/images/crossbag.jpeg",
  },
  {
    id: 9,
    title: "Smart Watch",
    price: 200,
    category: "Accessories",
    image: "/images/smartwatch.jpeg",
  },
  {
    id: 10,
    title: "Silver Chain Necklace",
    price: 45,
    category: "Accessories",
    image: "/images/chain.jpeg",
  },
];